### ISSUE TITLE
Missing error handler

### ISSUE THREAD

**Issue by milotheirself** [martinring/markdown-it-metadata-block#1]
I'd like to propose adding a parameter to `MetadataOptions` to allow the option of whether parsing errors can be ignored or should be logged to the console.
 
https://github.com/martinring/markdown-it-metadata-block/blob/298d7d140935b6807bd3c1fd8675621be50e58d9/src/index.ts#L32-L34

```ts
// ...
interface MetadataOptions { 
   parseMetadata: (src: string) => any, 
   meta?: object 
   debug?: boolean
} 
// ...
```

```ts
// ...
} catch (error) {
  if (options?.debug) console.warn(error); // already contains an descriptive error message
  return false;
}
// ...
```

**Comment by martinring** [comment]
Thank You for Your suggestion. However, I believe this can easily be achieved by handling the error on the user level. This approach has the advantage that any kind of logging can be used. Especially in the node context, logging to the console by default is no good practice in my opinion. 

Example:

````ts
let debug = true
md.use(metadata_block, {
  parseMetadata: (src) => {
    try {
      return doTheRealParsing()
    } catch (error) {
      if (debug) console.warn(error);
      return false
    }
  }
})
````
